spring:
  application:
    name: procurement-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: inventory_user
    password: inventory_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topics:
      stock-event: stock-event
      receive-goods: receive-goods
    group-id:
      procurement: procurement-group

server:
  port: 8081