spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: inventory_user
    password: inventory_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:9092

app:
  security:
    jwt:
      secret: mySuperSecretKeyThatIsAtLeast32CharactersLong
      expiration: 3600000
  kafka:
     topics:
       stock-event: stock-event
       stock-event-dlt: stock-event-dlt
     group-id:
       inventory: inventory-group

server:
  port: 8080
